"""initial schema

Revision ID: 4ba5ff8d031c
Revises: 
Create Date: 2026-09-12 16:43:54.553647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# 自定义列类型（UTCDateTime）会被 autogenerate 渲染成全限定名，缺此 import 会 NameError
import socialmedia_agent.database.base  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '4ba5ff8d031c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_id', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('owner_type', sa.String(length=16), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_canonical_id'), ['canonical_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_platform'), ['platform'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('first_seen', socialmedia_agent.database.base.UTCDateTime(), nullable=True),
    sa.Column('last_seen', socialmedia_agent.database.base.UTCDateTime(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('sentiment', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_keyword'), ['keyword'], unique=False)

    op.create_table('contents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_content_id', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('publish_time', socialmedia_agent.database.base.UTCDateTime(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.canonical_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_canonical_id'), ['canonical_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_contents_platform'), ['platform'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('metric_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('captured_at', socialmedia_agent.database.base.UTCDateTime(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.canonical_id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.canonical_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_platform'), ['platform'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_platform'))
        batch_op.drop_index(batch_op.f('ix_metrics_metric_type'))
        batch_op.drop_index(batch_op.f('ix_metrics_content_id'))
        batch_op.drop_index(batch_op.f('ix_metrics_captured_at'))
        batch_op.drop_index(batch_op.f('ix_metrics_account_id'))

    op.drop_table('metrics')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_platform'))
        batch_op.drop_index(batch_op.f('ix_contents_canonical_id'))
        batch_op.drop_index(batch_op.f('ix_contents_account_id'))

    op.drop_table('contents')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_keyword'))

    op.drop_table('topics')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_platform'))
        batch_op.drop_index(batch_op.f('ix_accounts_canonical_id'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
