"""add observation tables

Revision ID: 9f54b0f58482
Revises: 92d718789fd8
Create Date: 2026-09-13 15:43:18.646596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Custom column types (e.g. UTCDateTime) are rendered fully-qualified by
# autogenerate, so this import must be present or the migration raises NameError.
import socialmedia_agent.database.base  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '9f54b0f58482'
down_revision: Union[str, Sequence[str], None] = '92d718789fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(name: str) -> bool:
    """表是否已存在。

    **必须做存在性守卫**：upgrade_to_head 收养由 create_all 建的既有库时，
    会 stamp 基线（第一条迁移）后重跑**全部增量迁移**；而 create_all 建出的库
    已经是**最新 schema**——它连本次要新增的表都已经有了。
    不加守卫就会 "table already exists"（真实踩过，见 docs/issues.md #16）。
    这与 92d718789fd8（drop comments）的存在性守卫是同一条约定。
    """
    return name in sa.inspect(op.get_bind()).get_table_names()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table('topic_observations'):
        op.create_table('topic_observations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('keyword', sa.String(length=128), nullable=False),
        sa.Column('platforms', sa.JSON(), nullable=False),
        sa.Column('post_count', sa.Integer(), nullable=False),
        sa.Column('observed_at', socialmedia_agent.database.base.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('topic_observations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_topic_observations_keyword'), ['keyword'], unique=False)
            batch_op.create_index(batch_op.f('ix_topic_observations_observed_at'), ['observed_at'], unique=False)

    if not _has_table('metric_observations'):
        op.create_table('metric_observations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('content_id', sa.String(length=255), nullable=True),
        sa.Column('account_id', sa.String(length=255), nullable=True),
        sa.Column('platform', sa.String(length=32), nullable=False),
        sa.Column('metric_type', sa.String(length=16), nullable=False),
        sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column('observed_at', socialmedia_agent.database.base.UTCDateTime(), nullable=False),
        sa.Column('source', sa.String(length=32), nullable=False),
        sa.Column('raw_value', sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.canonical_id'], ),
        sa.ForeignKeyConstraint(['content_id'], ['contents.canonical_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('metric_observations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_metric_observations_account_id'), ['account_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_metric_observations_content_id'), ['content_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_metric_observations_metric_type'), ['metric_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_metric_observations_observed_at'), ['observed_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_metric_observations_platform'), ['platform'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema（同样做存在性守卫，保证可重复执行）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _has_table('metric_observations'):
        return
    with op.batch_alter_table('metric_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_observations_platform'))
        batch_op.drop_index(batch_op.f('ix_metric_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_metric_observations_metric_type'))
        batch_op.drop_index(batch_op.f('ix_metric_observations_content_id'))
        batch_op.drop_index(batch_op.f('ix_metric_observations_account_id'))

    op.drop_table('metric_observations')
    if not _has_table('topic_observations'):
        return
    with op.batch_alter_table('topic_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_topic_observations_keyword'))

    op.drop_table('topic_observations')
    # ### end Alembic commands ###
